In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("csv/2016 Men's Basketball.csv")
df.head(20)

,Overall Record: 27-6 Conf: 17-3 Home: 15-3 Away: 9-3 Neutral: 3-0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,#,Player,NaN,GP-GS,NaN,MIN,NaN,AVG,NaN,FG FG-FGA,...,PF,DQ,A,TO,BLK,STL,PTS,AVG,NaN,NaN
1,13,"Klie, Adam",NaN,33-33,NaN,1048,NaN,31.8,NaN,188-373,...,94,3,154,74,6,26,510,15.5,NaN,NaN
2,44,"Hansen, Chris",NaN,31-30,NaN,700,NaN,22.6,NaN,143-283,...,69,0,21,51,22,5,387,12.5,NaN,NaN
3,14,"Oshita, Christian",NaN,33-33,NaN,868,NaN,26.3,NaN,126-268,...,102,4,34,38,4,11,360,10.9,NaN,NaN
4,01,"Lipovic, Aleks",NaN,25-18,NaN,537,NaN,21.5,NaN,71-162,...,41,0,40,14,2,10,222,8.9,NaN,NaN
5,11,"Everman, Scott",NaN,33-5,NaN,623,NaN,18.9,NaN,79-182,...,48,1,18,24,8,13,239,7.2,NaN,NaN
6,05,"Buaku, George",NaN,33-32,NaN,956,NaN,29.0,NaN,64-139,...,75,2,82,23,5,26,188,5.7,NaN,NaN
7,10,"Ballestero, Anthony",NaN,33-1,NaN,693,NaN,21.0,NaN,43-121,...,52,1,61,30,0,22,165,5.0,NaN,NaN
8,22,"Patton, Eric",NaN,9-9,NaN,184,NaN,20.4,NaN,20-42,...,18,0,6,9,2,4,44,4.9,NaN,NaN
9,24,"Cox, Koree",NaN,13-1,NaN,86,NaN,6.6,NaN,14-40,...,9,0,3,8,0,3,45,3.5,NaN,NaN
10,33,"Shoemaker, Michael",NaN,32-0,NaN,340,NaN,10.6,NaN,42-94,...,54,1,9,16,10,4,99,3.1,NaN,NaN
11,15,"Brooks, Joshua",NaN,21-0,NaN,202,NaN,9.6,NaN,21-45,...,21,1,13,16,4,13,60,2.9,NaN,NaN
12,03,"Rico, Ben",NaN,17-0,NaN,101,NaN,5.9,NaN,8-29,...,7,0,7,1,1,3,30,1.8,NaN,NaN
13,25,"Fraser, Kenny",NaN,23-3,NaN,262,NaN,11.4,NaN,16-49,...,24,0,5,8,3,6,37,1.6,NaN,NaN
14,Total,NaN,NaN,33,NaN,6600,NaN,200.0,NaN,835-1827,...,615,13,453,328,67,146,2386,72.30,NaN,NaN
15,Opponents,NaN,NaN,NaN,NaN,6600,NaN,200.0,NaN,705-1713,...,558,8,283,342,108,139,2122,64.30,NaN,NaN
16,Team Statistics UCSD ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,SCORING,NaN,NaN,2386,NaN,NaN,2122,NaN,NaN,NaN,...,NaN,NaN,62-55,NaN,NaN,NaN,512,NaN,NaN,NaN
18,Points Per Game,NaN,NaN,72.3,NaN,NaN,64.3,NaN,NaN,NaN,...,NaN,NaN,70-67,NaN,NaN,NaN,232,NaN,NaN,NaN
19,Scoring Margin,NaN,NaN,8.0,NaN,NaN,–,NaN,NaN,NaN,...,NaN,NaN,82-68,NaN,NaN,NaN,266,NaN,NaN,NaN

In [3]:
df = pd.read_excel("2016 Men's Basketball.xlsx")
df.head(20)

,Overall Record: 27-6 Conf: 17-3 Home: 15-3 Away: 9-3 Neutral: 3-0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,#,Player,NaN,GP-GS,NaN,MIN,NaN,AVG,NaN,FG FG-FGA,...,NaN,AVG,PF,DQ,A,TO,BLK,STL,PTS,AVG
1,13,"Klie, Adam",NaN,33-33,NaN,1048,NaN,31.8,NaN,188-373,...,207,6.3,94,3,154,74,6,26,510,15.5
2,44,"Hansen, Chris",NaN,31-30,NaN,700,NaN,22.6,NaN,143-283,...,186,6,69,0,21,51,22,5,387,12.5
3,14,"Oshita, Christian",NaN,33-33,NaN,868,NaN,26.3,NaN,126-268,...,185,5.6,102,4,34,38,4,11,360,10.9
4,1,"Lipovic, Aleks",NaN,25-18,NaN,537,NaN,21.5,NaN,71-162,...,42,1.7,41,0,40,14,2,10,222,8.9
5,11,"Everman, Scott",NaN,33-5,NaN,623,NaN,18.9,NaN,79-182,...,88,2.7,48,1,18,24,8,13,239,7.2
6,5,"Buaku, George",NaN,33-32,NaN,956,NaN,29,NaN,64-139,...,82,2.5,75,2,82,23,5,26,188,5.7
7,10,"Ballestero, Anthony",NaN,33-1,NaN,693,NaN,21,NaN,43-121,...,43,1.3,52,1,61,30,0,22,165,5
8,22,"Patton, Eric",NaN,9-9,NaN,184,NaN,20.4,NaN,20-42,...,36,4,18,0,6,9,2,4,44,4.9
9,24,"Cox, Koree",NaN,13-1,NaN,86,NaN,6.6,NaN,14-40,...,15,1.2,9,0,3,8,0,3,45,3.5
10,33,"Shoemaker, Michael",NaN,32-0,NaN,340,NaN,10.6,NaN,42-94,...,82,2.6,54,1,9,16,10,4,99,3.1
11,15,"Brooks, Joshua",NaN,21-0,NaN,202,NaN,9.6,NaN,21-45,...,22,1,21,1,13,16,4,13,60,2.9
12,3,"Rico, Ben",NaN,17-0,NaN,101,NaN,5.9,NaN,8-29,...,12,0.7,7,0,7,1,1,3,30,1.8
13,25,"Fraser, Kenny",NaN,23-3,NaN,262,NaN,11.4,NaN,16-49,...,55,2.4,24,0,5,8,3,6,37,1.6
14,Total,NaN,NaN,33,NaN,6600,NaN,200,NaN,835-1827,...,1169,35.4,615,13,453,328,67,146,2386,72.3
15,Opponents,NaN,NaN,NaN,NaN,6600,NaN,200,NaN,705-1713,...,1024,31,558,8,283,342,108,139,2122,64.3
16,Team Statistics UCSD ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,SCORING,NaN,NaN,2386,NaN,NaN,2122,NaN,NaN,NaN,...,W,NaN,NaN,NaN,62-55,NaN,NaN,NaN,512,NaN
18,Points Per Game,NaN,NaN,72.3,NaN,NaN,64.3,NaN,NaN,NaN,...,W,NaN,NaN,NaN,70-67,NaN,NaN,NaN,232,NaN
19,Scoring Margin,NaN,NaN,8,NaN,NaN,–,NaN,NaN,NaN,...,W,NaN,NaN,NaN,82-68,NaN,NaN,NaN,266,NaN